/**
 * @file nvm_config_id.h
 * @copyright Futavis GmbH, Aachen 2020 - alle Rechte vorbehalten
 * @brief Short description
 * @details
 *  <b>Beschreibung</b>
 *
 *  Detaillierte Beschreibung des Moduls
 *
 */

#pragma once


#define NVM_CONFIG_BLOCK_ID   1
#define NVM_CONFIG_BLOCK_SIZE 4u


#define NVM_BOOTLOADER_BLOCK_ID   2
#define NVM_BOOTLOADER_BLOCK_SIZE 128u


#define NVM_ECU_IDENTIFICATION_BLOCK_ID   3
#define NVM_ECU_IDENTIFICATION_BLOCK_SIZE 100u


#define NVM_TASK_BLOCKED_MONITOR_BLOCK_ID   4
#define NVM_TASK_BLOCKED_MONITOR_BLOCK_SIZE 32u


#define NVM_TASK_ALIVE_MONITOR_BLOCK_ID   5
#define NVM_TASK_ALIVE_MONITOR_BLOCK_SIZE 700u


#define NVM_UDS_SECURITY_ACCESS_BLOCK_ID   6
#define NVM_UDS_SECURITY_ACCESS_BLOCK_SIZE 8u


#define NVM_AFE_CHECK_BLOCK_ID   7
#define NVM_AFE_CHECK_BLOCK_SIZE 328u


#define NVM_MODULE_VOLTAGE_TEMPERATURE_HISTOGRAM_BLOCK_ID   8
#define NVM_MODULE_VOLTAGE_TEMPERATURE_HISTOGRAM_BLOCK_SIZE 700u


#define NVM_HEATING_CURRENT_HISTOGRAM_1_BLOCK_ID   9
#define NVM_HEATING_CURRENT_HISTOGRAM_1_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_2_BLOCK_ID   10
#define NVM_HEATING_CURRENT_HISTOGRAM_2_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_3_BLOCK_ID   11
#define NVM_HEATING_CURRENT_HISTOGRAM_3_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_4_BLOCK_ID   12
#define NVM_HEATING_CURRENT_HISTOGRAM_4_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_5_BLOCK_ID   13
#define NVM_HEATING_CURRENT_HISTOGRAM_5_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_6_BLOCK_ID   14
#define NVM_HEATING_CURRENT_HISTOGRAM_6_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_7_BLOCK_ID   15
#define NVM_HEATING_CURRENT_HISTOGRAM_7_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_8_BLOCK_ID   16
#define NVM_HEATING_CURRENT_HISTOGRAM_8_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_9_BLOCK_ID   17
#define NVM_HEATING_CURRENT_HISTOGRAM_9_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_10_BLOCK_ID   18
#define NVM_HEATING_CURRENT_HISTOGRAM_10_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_11_BLOCK_ID   19
#define NVM_HEATING_CURRENT_HISTOGRAM_11_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_12_BLOCK_ID   20
#define NVM_HEATING_CURRENT_HISTOGRAM_12_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_13_BLOCK_ID   21
#define NVM_HEATING_CURRENT_HISTOGRAM_13_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_14_BLOCK_ID   22
#define NVM_HEATING_CURRENT_HISTOGRAM_14_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_15_BLOCK_ID   23
#define NVM_HEATING_CURRENT_HISTOGRAM_15_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_16_BLOCK_ID   24
#define NVM_HEATING_CURRENT_HISTOGRAM_16_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_17_BLOCK_ID   25
#define NVM_HEATING_CURRENT_HISTOGRAM_17_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_18_BLOCK_ID   26
#define NVM_HEATING_CURRENT_HISTOGRAM_18_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_19_BLOCK_ID   27
#define NVM_HEATING_CURRENT_HISTOGRAM_19_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_20_BLOCK_ID   28
#define NVM_HEATING_CURRENT_HISTOGRAM_20_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_21_BLOCK_ID   29
#define NVM_HEATING_CURRENT_HISTOGRAM_21_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_22_BLOCK_ID   30
#define NVM_HEATING_CURRENT_HISTOGRAM_22_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_23_BLOCK_ID   31
#define NVM_HEATING_CURRENT_HISTOGRAM_23_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_24_BLOCK_ID   32
#define NVM_HEATING_CURRENT_HISTOGRAM_24_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_25_BLOCK_ID   33
#define NVM_HEATING_CURRENT_HISTOGRAM_25_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_26_BLOCK_ID   34
#define NVM_HEATING_CURRENT_HISTOGRAM_26_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_27_BLOCK_ID   35
#define NVM_HEATING_CURRENT_HISTOGRAM_27_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_28_BLOCK_ID   36
#define NVM_HEATING_CURRENT_HISTOGRAM_28_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_29_BLOCK_ID   37
#define NVM_HEATING_CURRENT_HISTOGRAM_29_BLOCK_SIZE 40u


#define NVM_HEATING_CURRENT_HISTOGRAM_30_BLOCK_ID   38
#define NVM_HEATING_CURRENT_HISTOGRAM_30_BLOCK_SIZE 40u


#define NVM_TEMPERATURE_HISTOGRAM_1_BLOCK_ID   39
#define NVM_TEMPERATURE_HISTOGRAM_1_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_2_BLOCK_ID   40
#define NVM_TEMPERATURE_HISTOGRAM_2_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_3_BLOCK_ID   41
#define NVM_TEMPERATURE_HISTOGRAM_3_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_4_BLOCK_ID   42
#define NVM_TEMPERATURE_HISTOGRAM_4_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_5_BLOCK_ID   43
#define NVM_TEMPERATURE_HISTOGRAM_5_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_6_BLOCK_ID   44
#define NVM_TEMPERATURE_HISTOGRAM_6_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_7_BLOCK_ID   45
#define NVM_TEMPERATURE_HISTOGRAM_7_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_8_BLOCK_ID   46
#define NVM_TEMPERATURE_HISTOGRAM_8_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_9_BLOCK_ID   47
#define NVM_TEMPERATURE_HISTOGRAM_9_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_10_BLOCK_ID   48
#define NVM_TEMPERATURE_HISTOGRAM_10_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_11_BLOCK_ID   49
#define NVM_TEMPERATURE_HISTOGRAM_11_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_12_BLOCK_ID   50
#define NVM_TEMPERATURE_HISTOGRAM_12_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_13_BLOCK_ID   51
#define NVM_TEMPERATURE_HISTOGRAM_13_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_14_BLOCK_ID   52
#define NVM_TEMPERATURE_HISTOGRAM_14_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_15_BLOCK_ID   53
#define NVM_TEMPERATURE_HISTOGRAM_15_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_16_BLOCK_ID   54
#define NVM_TEMPERATURE_HISTOGRAM_16_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_17_BLOCK_ID   55
#define NVM_TEMPERATURE_HISTOGRAM_17_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_18_BLOCK_ID   56
#define NVM_TEMPERATURE_HISTOGRAM_18_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_19_BLOCK_ID   57
#define NVM_TEMPERATURE_HISTOGRAM_19_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_20_BLOCK_ID   58
#define NVM_TEMPERATURE_HISTOGRAM_20_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_21_BLOCK_ID   59
#define NVM_TEMPERATURE_HISTOGRAM_21_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_22_BLOCK_ID   60
#define NVM_TEMPERATURE_HISTOGRAM_22_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_23_BLOCK_ID   61
#define NVM_TEMPERATURE_HISTOGRAM_23_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_24_BLOCK_ID   62
#define NVM_TEMPERATURE_HISTOGRAM_24_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_25_BLOCK_ID   63
#define NVM_TEMPERATURE_HISTOGRAM_25_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_26_BLOCK_ID   64
#define NVM_TEMPERATURE_HISTOGRAM_26_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_27_BLOCK_ID   65
#define NVM_TEMPERATURE_HISTOGRAM_27_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_28_BLOCK_ID   66
#define NVM_TEMPERATURE_HISTOGRAM_28_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_29_BLOCK_ID   67
#define NVM_TEMPERATURE_HISTOGRAM_29_BLOCK_SIZE 220u


#define NVM_TEMPERATURE_HISTOGRAM_30_BLOCK_ID   68
#define NVM_TEMPERATURE_HISTOGRAM_30_BLOCK_SIZE 220u


#define NVM_VOLTAGE_HISTOGRAM_1_BLOCK_ID   69
#define NVM_VOLTAGE_HISTOGRAM_1_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_2_BLOCK_ID   70
#define NVM_VOLTAGE_HISTOGRAM_2_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_3_BLOCK_ID   71
#define NVM_VOLTAGE_HISTOGRAM_3_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_4_BLOCK_ID   72
#define NVM_VOLTAGE_HISTOGRAM_4_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_5_BLOCK_ID   73
#define NVM_VOLTAGE_HISTOGRAM_5_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_6_BLOCK_ID   74
#define NVM_VOLTAGE_HISTOGRAM_6_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_7_BLOCK_ID   75
#define NVM_VOLTAGE_HISTOGRAM_7_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_8_BLOCK_ID   76
#define NVM_VOLTAGE_HISTOGRAM_8_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_9_BLOCK_ID   77
#define NVM_VOLTAGE_HISTOGRAM_9_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_10_BLOCK_ID   78
#define NVM_VOLTAGE_HISTOGRAM_10_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_11_BLOCK_ID   79
#define NVM_VOLTAGE_HISTOGRAM_11_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_12_BLOCK_ID   80
#define NVM_VOLTAGE_HISTOGRAM_12_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_13_BLOCK_ID   81
#define NVM_VOLTAGE_HISTOGRAM_13_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_14_BLOCK_ID   82
#define NVM_VOLTAGE_HISTOGRAM_14_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_15_BLOCK_ID   83
#define NVM_VOLTAGE_HISTOGRAM_15_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_16_BLOCK_ID   84
#define NVM_VOLTAGE_HISTOGRAM_16_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_17_BLOCK_ID   85
#define NVM_VOLTAGE_HISTOGRAM_17_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_18_BLOCK_ID   86
#define NVM_VOLTAGE_HISTOGRAM_18_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_19_BLOCK_ID   87
#define NVM_VOLTAGE_HISTOGRAM_19_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_20_BLOCK_ID   88
#define NVM_VOLTAGE_HISTOGRAM_20_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_21_BLOCK_ID   89
#define NVM_VOLTAGE_HISTOGRAM_21_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_22_BLOCK_ID   90
#define NVM_VOLTAGE_HISTOGRAM_22_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_23_BLOCK_ID   91
#define NVM_VOLTAGE_HISTOGRAM_23_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_24_BLOCK_ID   92
#define NVM_VOLTAGE_HISTOGRAM_24_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_25_BLOCK_ID   93
#define NVM_VOLTAGE_HISTOGRAM_25_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_26_BLOCK_ID   94
#define NVM_VOLTAGE_HISTOGRAM_26_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_27_BLOCK_ID   95
#define NVM_VOLTAGE_HISTOGRAM_27_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_28_BLOCK_ID   96
#define NVM_VOLTAGE_HISTOGRAM_28_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_29_BLOCK_ID   97
#define NVM_VOLTAGE_HISTOGRAM_29_BLOCK_SIZE 292u


#define NVM_VOLTAGE_HISTOGRAM_30_BLOCK_ID   98
#define NVM_VOLTAGE_HISTOGRAM_30_BLOCK_SIZE 292u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_1_BLOCK_ID   99
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_1_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_2_BLOCK_ID   100
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_2_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_3_BLOCK_ID   101
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_3_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_4_BLOCK_ID   102
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_4_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_5_BLOCK_ID   103
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_5_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_6_BLOCK_ID   104
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_6_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_7_BLOCK_ID   105
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_7_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_8_BLOCK_ID   106
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_8_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_9_BLOCK_ID   107
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_9_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_10_BLOCK_ID   108
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_10_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_11_BLOCK_ID   109
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_11_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_12_BLOCK_ID   110
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_12_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_13_BLOCK_ID   111
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_13_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_14_BLOCK_ID   112
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_14_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_15_BLOCK_ID   113
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_15_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_16_BLOCK_ID   114
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_16_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_17_BLOCK_ID   115
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_17_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_18_BLOCK_ID   116
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_18_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_19_BLOCK_ID   117
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_19_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_20_BLOCK_ID   118
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_20_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_21_BLOCK_ID   119
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_21_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_22_BLOCK_ID   120
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_22_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_23_BLOCK_ID   121
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_23_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_24_BLOCK_ID   122
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_24_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_25_BLOCK_ID   123
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_25_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_26_BLOCK_ID   124
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_26_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_27_BLOCK_ID   125
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_27_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_28_BLOCK_ID   126
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_28_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_29_BLOCK_ID   127
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_29_BLOCK_SIZE 32u


#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_30_BLOCK_ID   128
#define NVM_VOLTAGE_VIOLATION_HISTOGRAM_30_BLOCK_SIZE 32u


#define NVM_ID_ALLOCATION_BLOCK_ID   129
#define NVM_ID_ALLOCATION_BLOCK_SIZE 20u


#define NVM_WARRANTY_DATA_BLOCK_ID   130
#define NVM_WARRANTY_DATA_BLOCK_SIZE 1200u


#define NVM_STATE_FUNCTIONS_BLOCK_ID   131
#define NVM_STATE_FUNCTIONS_BLOCK_SIZE 68u


#define NVM_CPS_DATA_BLOCK_ID   132
#define NVM_CPS_DATA_BLOCK_SIZE 64u


#define NVM_PROTOCOL_SELECTION_DATA_BLOCK_ID   133
#define NVM_PROTOCOL_SELECTION_DATA_BLOCK_SIZE 12u


#define NVM_BATTERY_CURRENT_TEMPERATURE_HISTOGRAM_BLOCK_ID   134
#define NVM_BATTERY_CURRENT_TEMPERATURE_HISTOGRAM_BLOCK_SIZE 1580u


#define NVM_CONTACTOR_HISTOGRAM_BLOCK_ID   135
#define NVM_CONTACTOR_HISTOGRAM_BLOCK_SIZE 320u


#define NVM_CURRENT_VIOLATION_HISTOGRAM_BLOCK_ID   136
#define NVM_CURRENT_VIOLATION_HISTOGRAM_BLOCK_SIZE 148u


#define NVM_PERIODIC_WAKE_UP_BLOCK_ID   137
#define NVM_PERIODIC_WAKE_UP_BLOCK_SIZE 20u


#define NVM_TASK_PERFORMANCE_MEASUREMENT_BLOCK_ID   138
#define NVM_TASK_PERFORMANCE_MEASUREMENT_BLOCK_SIZE 1944u


#define NVM_STACK_USAGE_MONITOR_BLOCK_ID   139
#define NVM_STACK_USAGE_MONITOR_BLOCK_SIZE 48u


#define NVM_LIB_IDENTIFICATION_BLOCK_ID   140
#define NVM_LIB_IDENTIFICATION_BLOCK_SIZE 2964u


#define NVM_DEM_UDS_META_BLOCK_ID   141
#define NVM_DEM_UDS_META_BLOCK_SIZE 412u


#define NVM_DTC_SNAPSHOT_BLOCK_ID   142
#define NVM_DTC_SNAPSHOT_BLOCK_SIZE 28u


#define NVM_DTC_EXTENDED_DATA_BLOCK_ID   143
#define NVM_DTC_EXTENDED_DATA_BLOCK_SIZE 12u


#define NVM_TIMESTAMP_BLOCK_ID   144
#define NVM_TIMESTAMP_BLOCK_SIZE 12u


#define NVM_VEHICLE_MANUFACTURER_DATA_BLOCK_ID   145
#define NVM_VEHICLE_MANUFACTURER_DATA_BLOCK_SIZE 20u


#define NVM_ENERGY_COUNTER_BLOCK_ID   146
#define NVM_ENERGY_COUNTER_BLOCK_SIZE 28u


#define NVM_ECU_DATE_DATA_BLOCK_ID   147
#define NVM_ECU_DATE_DATA_BLOCK_SIZE 8u


#define NVM_DIAGNOSTIC_TIMES_BLOCK_ID   148
#define NVM_DIAGNOSTIC_TIMES_BLOCK_SIZE 32u


#define NVM_CPS_MONITOR_BLOCK_ID   149
#define NVM_CPS_MONITOR_BLOCK_SIZE 16u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_1_BLOCK_ID   150
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_1_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_2_BLOCK_ID   151
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_2_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_3_BLOCK_ID   152
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_3_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_4_BLOCK_ID   153
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_4_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_5_BLOCK_ID   154
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_5_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_6_BLOCK_ID   155
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_6_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_7_BLOCK_ID   156
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_7_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_8_BLOCK_ID   157
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_8_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_9_BLOCK_ID   158
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_9_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_10_BLOCK_ID   159
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_10_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_11_BLOCK_ID   160
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_11_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_12_BLOCK_ID   161
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_12_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_13_BLOCK_ID   162
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_13_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_14_BLOCK_ID   163
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_14_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_15_BLOCK_ID   164
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_15_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_16_BLOCK_ID   165
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_16_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_17_BLOCK_ID   166
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_17_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_18_BLOCK_ID   167
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_18_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_19_BLOCK_ID   168
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_19_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_20_BLOCK_ID   169
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_20_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_21_BLOCK_ID   170
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_21_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_22_BLOCK_ID   171
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_22_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_23_BLOCK_ID   172
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_23_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_24_BLOCK_ID   173
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_24_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_25_BLOCK_ID   174
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_25_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_26_BLOCK_ID   175
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_26_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_27_BLOCK_ID   176
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_27_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_28_BLOCK_ID   177
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_28_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_29_BLOCK_ID   178
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_29_BLOCK_SIZE 28u


#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_30_BLOCK_ID   179
#define NVM_DOWNSCALED_VOLTAGE_TEMPERATURE_HISTOGRAM_30_BLOCK_SIZE 28u


#define NVM_KBS_INTERFACE_BLOCK_ID   180
#define NVM_KBS_INTERFACE_BLOCK_SIZE 40004u


#define NVM_EVENT_DATA_BLOCK_ID   181
#define NVM_EVENT_DATA_BLOCK_SIZE 28u


#define NVM_CURRENT_VIOLATION_LOG_HISTOGRAM_BLOCK_ID   182
#define NVM_CURRENT_VIOLATION_LOG_HISTOGRAM_BLOCK_SIZE 56u


#define NVM_BATTERY_CONTACTOR_HISTOGRAM_BLOCK_ID   183
#define NVM_BATTERY_CONTACTOR_HISTOGRAM_BLOCK_SIZE 196u


#define NVM_MASTER_PCB_TEMPERATURE_HISTOGRAM_BLOCK_ID   184
#define NVM_MASTER_PCB_TEMPERATURE_HISTOGRAM_BLOCK_SIZE 44u


#define NVM_SOC_TEMPERATURE_HISTOGRAM_BLOCK_ID   185
#define NVM_SOC_TEMPERATURE_HISTOGRAM_BLOCK_SIZE 228u


#define NVM_VOLTAGE_CONTACTOR_HISTOGRAM_BLOCK_ID   186
#define NVM_VOLTAGE_CONTACTOR_HISTOGRAM_BLOCK_SIZE 84u


#define NVM_TESTER_SERIAL_NUMBER_BLOCK_ID   187
#define NVM_TESTER_SERIAL_NUMBER_BLOCK_SIZE 48u


#define NVM_DEM_NVM_BLOCK_ID   188
#define NVM_DEM_NVM_BLOCK_SIZE 76u


#define NVM_SHUTDOWN_TIME_MEASUREMENT_BLOCK_ID   189
#define NVM_SHUTDOWN_TIME_MEASUREMENT_BLOCK_SIZE 12u
