/**
 * @file temperatureHistogram_config.c
 * @copyright (c) Futavis GmbH, Aachen 2020 - alle Rechte vorbehalten
 * @brief Short description
 * @details
 *  <b>Beschreibung</b>
 *
 *  Detaillierte Beschreibung des Moduls
 *
 */

/* Related Requirements: */
/**@req WHBMS-12986*/
/**@req WHBMS-12987*/
/**@req WHBMS-14362*/
/**@req WHBMS-14357*/
/**@req WHBMS-14358*/
/**@req WHBMS-14359*/
/**@req WHBMS-14362*/
/**@req WHBMS-14363*/
/**@req WHBMS-14364*/
/**@req WHBMS-14365*/
/**@req WHBMS-14366*/
/**@req WHBMS-14369*/
/**@req WHBMS-32721*/


//***************************************************************************//
//************************** INCLUDES ***************************************//
//***************************************************************************//
#include <stdint.h>
#include "temperatureHistogram.h"
#include "temperatureHistogram_config.h"
#include "task_cfg.h"
#include "module_config.h"


//***************************************************************************//
//************************** PRIVATE TYPEDEFS *******************************//
//***************************************************************************//


//***************************************************************************//
//************************** PRIVATE FUNCTION DECLARATIONS ******************//
//***************************************************************************//


//***************************************************************************//
//************************** PRIVATE VARIABLE DECLARATIONS ******************//
//***************************************************************************//

// @req CB-89282
MEM_SEC_PARAMETER int32_t temperatureHistogramLimitsOperation[] = {
    -20,
    -10,
    0,
    10,
    25,
    40,
    50,
    60,
};

// @req CB-78732 CB-78733
MEM_WARRANTYDATA TemperatureHistogramNvm temperatureHistogramCountersModule[BMS_CONFIG_MAX_NUMBER_OF_SLAVES] = { 0 };

const uint16_t WARRANTY_DATA_MIN_TEMPERATURE_OPERATION_SIZE = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MAX_TEMPERATURE_OPERATION_SIZE = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_AVG_TEMPERATURE_OPERATION_SIZE = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MIN_TEMPERATURE_STORAGE_SIZE   = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MAX_TEMPERATURE_STORAGE_SIZE   = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_AVG_TEMPERATURE_STORAGE_SIZE   = (sizeof(temperatureHistogramLimitsOperation) / sizeof(uint32_t) + 1u);

// @req CB-78736 CB-89286
const TemperatureHistogram temperatureHistograms[] = {
#if !defined(BMS_CONFIG_MAX_NUMBER_OF_SLAVES)
// cppcheck-suppress preprocessorErrorDirective ; BMS_CONFIG_MAX_NUMBER_OF_SLAVES is defined
#error missing or wrong configuration
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 1u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[0].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[0].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 2u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[1].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[1].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 3u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[2].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[2].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 4u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[3].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[3].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 5u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[4].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[4].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 6u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[5].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[5].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 7u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[6].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[6].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 8u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[7].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[7].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 9u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[8].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[8].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 10u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[9].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[9].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 11u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[10].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[10].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 12u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[11].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[11].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 13u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[12].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[12].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 14u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[13].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[13].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 15u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[14].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[14].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 16u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[15].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[15].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 17u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[16].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[16].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 18u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[17].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[17].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 19u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[18].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[18].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 20u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[19].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[19].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 21u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[20].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[20].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 22u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[21].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[21].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 23u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[22].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[22].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 24u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[23].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[23].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 25u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[24].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[24].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 26u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[25].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[25].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 27u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[26].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[26].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 28u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[27].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[27].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 29u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[28].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[28].counters.countershistogramAvgTemperatureStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 30u
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramMinTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramMinTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramMaxTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramMaxTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramAvgTemperatureOperational) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramAvgTemperatureOperational[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramMinTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramMinTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramMaxTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramMaxTemperatureStorage[0] },
    { .systemTemperatureLimits       = &temperatureHistogramLimitsOperation[0],
      .systemTemperatureLimitsLength = (sizeof(temperatureHistogramLimitsOperation) / sizeof(int32_t)) + 1U,
      .counterSize                   = sizeof(temperatureHistogramCountersModule[29].counters.countershistogramAvgTemperatureStorage) / sizeof(uint32_t),
      .counters                      = &temperatureHistogramCountersModule[29].counters.countershistogramAvgTemperatureStorage[0] },
#endif
};

const TemperatureHistogramConfig temperatureHistogramConfig = {
    .histograms         = temperatureHistograms,
    .numberOfHistograms = sizeof(temperatureHistograms) / sizeof(TemperatureHistogram)
};


//***************************************************************************//
//************************** PRIVATE FUNCTION DEFINITIONS *******************//
//***************************************************************************//


//***************************************************************************//
//************************** PUBLIC FUNCTION DEFINITIONS * ******************//
//***************************************************************************//
