/**
 * @file voltageViolationHistogram_config.c
 * @copyright (c) Futavis GmbH, Aachen 2020 - alle Rechte vorbehalten
 * @brief Short description
 * @details
 *  <b>Beschreibung</b>
 *
 *  Detaillierte Beschreibung des Moduls
 *
 */

//***************************************************************************//
//************************** INCLUDES ***************************************//
//***************************************************************************//
#include "voltageViolationHistogram.h"
#include "task_cfg.h"
#include <stdbool.h>
#include "stateFunctions.h"
#include "module_config.h"

//***************************************************************************//
//************************** PRIVATE TYPEDEFS *******************************//
//***************************************************************************//

//***************************************************************************//
//************************** PRIVATE FUNCTION DECLARATIONS ******************//
//***************************************************************************//

//***************************************************************************//
//************************** PRIVATE VARIABLE DECLARATIONS ******************//
//***************************************************************************//
MEM_SEC_PARAMETER uint16_t histogramViolationOperatingVoltageLimits[] = {
    2500,
    4150
};

MEM_SEC_PARAMETER uint16_t histogramDataViolationErrorValues01[] = {
    2,
    5
};

MEM_SEC_PARAMETER uint16_t histogramDataViolationErrorValues02[] = {
    8,
    45
};

MEM_SEC_PARAMETER int16_t histogramViolationTemperatureLimits[] = {
    -10,
    -25,
};

MEM_WARRANTYDATA VoltageViolationHistogramNvm voltageViolationHistogramCountersModule[BMS_CONFIG_MAX_NUMBER_OF_SLAVES] = { 0 };

MEM_WARRANTYDATA VoltageViolationHistogramRing voltageViolationHistogramRingModule[BMS_CONFIG_MAX_NUMBER_OF_SLAVES];

const uint16_t WARRANTY_DATA_CELL_VOLTAGE_VIOLATION_LOW_SIZE = VOLTAGE_VIOLATION_HISTOGRAM_COUNTER_SIZE;

const VoltageViolationHistogram voltageViolationHistograms[] = {
#if !defined(BMS_CONFIG_MAX_NUMBER_OF_SLAVES)
// cppcheck-suppress preprocessorErrorDirective ; BMS_CONFIG_MAX_NUMBER_OF_SLAVES is defined
#error missing or wrong configuration
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 1u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[0],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[0].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[0].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[0],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[0].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[0].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 2u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[1],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[1].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[1].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[1],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[1].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[1].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 3u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[2],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[2].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[2].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[2],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[2].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[2].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 4u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[3],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[3].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[3].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[3],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[3].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[3].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 5u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[4],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[4].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[4].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[4],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[4].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[4].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 6u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[5],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[5].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[5].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[5],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[5].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[5].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 7u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[6],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[6].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[6].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[6],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[6].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[6].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 8u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[7],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[7].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[7].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[7],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[7].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[7].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 9u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[8],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[8].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[8].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[8],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[8].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[8].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 10u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[9],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[9].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[9].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[9],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[9].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[9].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 11u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[10],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[10].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[10].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[10],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[10].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[10].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 12u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[11],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[11].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[11].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[11],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[11].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[11].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 13u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[12],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[12].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[12].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[12],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[12].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[12].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 14u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[13],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[13].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[13].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[13],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[13].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[13].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 15u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[14],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[14].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[14].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[14],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[14].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[14].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 16u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[15],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[15].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[15].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[15],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[15].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[15].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 17u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[16],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[16].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[16].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[16],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[16].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[16].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 18u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[17],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[17].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[17].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[17],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[17].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[17].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 19u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[18],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[18].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[18].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[18],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[18].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[18].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 20u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[19],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[19].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[19].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[19],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[19].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[19].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 21u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[20],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[20].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[20].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[20],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[20].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[20].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 22u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[21],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[21].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[21].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[21],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[21].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[21].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 23u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[22],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[22].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[22].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[22],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[22].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[22].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 24u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[23],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[23].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[23].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[23],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[23].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[23].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 25u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[24],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[24].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[24].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[24],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[24].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[24].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 26u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[25],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[25].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[25].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[25],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[25].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[25].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 27u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[26],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[26].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[26].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[26],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[26].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[26].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 28u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[27],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[27].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[27].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[27],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[27].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[27].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 29u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[28],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[28].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[28].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[28],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[28].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[28].counters.countersHistogramHighVoltageViolation[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 30u
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[29],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[29].counters.countersHistogramLowVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[29].counters.countersHistogramLowVoltageViolation[0] },
    { .systemVoltageViolationLimits            = &histogramViolationOperatingVoltageLimits[0],
      .systemVoltageViolationLimitsLength      = (sizeof(histogramViolationOperatingVoltageLimits) / sizeof(uint16_t)),
      .systemTemperatureLimits                 = &histogramViolationTemperatureLimits[0],
      .systemTemperatureLimitsLength           = (sizeof(histogramViolationTemperatureLimits) / sizeof(int16_t)),
      .systemVoltageErrorValuesCharge          = &histogramDataViolationErrorValues02[0],
      .systemVoltageErrorValuesChargeLength    = (sizeof(histogramDataViolationErrorValues02) / sizeof(int16_t)),
      .systemVoltageErrorValuesDischarge       = &histogramDataViolationErrorValues01[0],
      .systemVoltageErrorValuesDischargeLength = (sizeof(histogramDataViolationErrorValues01) / sizeof(int16_t)),
      .ring                                    = &voltageViolationHistogramRingModule[29],
      .counterSize                             = sizeof(voltageViolationHistogramCountersModule[29].counters.countersHistogramHighVoltageViolation) / sizeof(uint32_t),
      .counters                                = &voltageViolationHistogramCountersModule[29].counters.countersHistogramHighVoltageViolation[0] },
#endif
};

const uint16_t WARRANTY_DATA_CELL_VOLTAGE_VIOLATION_HIGH_SIZE = VOLTAGE_VIOLATION_HISTOGRAM_COUNTER_SIZE;

const VoltageViolationHistogramConfig voltageViolationHistogramConfig = {
    .histograms         = voltageViolationHistograms,
    .numberOfHistograms = sizeof(voltageViolationHistograms) / sizeof(VoltageViolationHistogram)
};

//***************************************************************************//
//************************** PRIVATE FUNCTION DEFINITIONS *******************//
//***************************************************************************//

//***************************************************************************//
//************************** PUBLIC FUNCTION DEFINITIONS * ******************//
//***************************************************************************//
