/**
 * @file voltageHistogram_config.c
 * @copyright (c) Futavis GmbH, Aachen 2020 - alle Rechte vorbehalten
 * @brief Short description
 * @details
 *  <b>Beschreibung</b>
 *
 *  Detaillierte Beschreibung des Moduls
 *
 */

/**@req WHBMS-12982*/
/**@req WHBMS-12983*/
/**@req WHBMS-14339*/
/**@req WHBMS-14340*/
/**@req WHBMS-14341*/
/**@req WHBMS-14343*/
/**@req WHBMS-14346*/
/**@req WHBMS-14349*/
/**@req WHBMS-14350*/
/**@req WHBMS-14351*/
/**@req WHBMS-14355*/
/**@req WHBMS-24774*/
/**@req WHBMS-39776*/

//***************************************************************************//
//************************** INCLUDES ***************************************//
//***************************************************************************//
#include "voltageHistogram.h"
#include "voltageHistogram_config.h"
#include "task_cfg.h"
#include <stdint.h>

#include "module_config.h"

//***************************************************************************//
//************************** PRIVATE TYPEDEFS *******************************//
//***************************************************************************//

//***************************************************************************//
//************************** PRIVATE FUNCTION DECLARATIONS ******************//
//***************************************************************************//

//***************************************************************************//
//************************** PRIVATE VARIABLE DECLARATIONS ******************//
//***************************************************************************//

// @req CB-89332
MEM_SEC_PARAMETER int32_t voltageHistogramLimitsCellVoltage[] = {
    2000,
    2500,
    3000,
    3300,
    3700,
    4000,
    4050,
    4070,
    4100,
    4150,
    4200
};

// @req CB-78710 CB-78711 CB-78714
MEM_WARRANTYDATA VoltageHistogramNvm voltageHistogramCountersModule[BMS_CONFIG_MAX_NUMBER_OF_SLAVES] = { 0 };

const uint16_t WARRANTY_DATA_MIN_CELL_VOLTAGE_OPERATION_SIZE = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MAX_CELL_VOLTAGE_OPERATION_SIZE = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_AVG_CELL_VOLTAGE_OPERATION_SIZE = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MIN_CELL_VOLTAGE_STORAGE_SIZE   = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_MAX_CELL_VOLTAGE_STORAGE_SIZE   = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);
const uint16_t WARRANTY_DATA_AVG_CELL_VOLTAGE_STORAGE_SIZE   = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(uint32_t) + 1u);

// @req CB-89329
const VoltageHistogram voltageHistograms[] = {
#if !defined(BMS_CONFIG_MAX_NUMBER_OF_SLAVES)
// cppcheck-suppress preprocessorErrorDirective ; BMS_CONFIG_MAX_NUMBER_OF_SLAVES is defined
#error missing or wrong configuration
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 1u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[0].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[0].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 2u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[1].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[1].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 3u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[2].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[2].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 4u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[3].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[3].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 5u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[4].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[4].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 6u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[5].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[5].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 7u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[6].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[6].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 8u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[7].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[7].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 9u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[8].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[8].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 10u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[9].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[9].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 11u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[10].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[10].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 12u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[11].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[11].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 13u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[12].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[12].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 14u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[13].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[13].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 15u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[14].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[14].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 16u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[15].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[15].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 17u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[16].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[16].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 18u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[17].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[17].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 19u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[18].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[18].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 20u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[19].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[19].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 21u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[20].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[20].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 22u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[21].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[21].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 23u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[22].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[22].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 24u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[23].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[23].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 25u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[24].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[24].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 26u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[25].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[25].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 27u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[26].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[26].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 28u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[27].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[27].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 29u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[28].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[28].counters.countershistogramAvgVoltageStorage[0] },
#endif
#if BMS_CONFIG_MAX_NUMBER_OF_SLAVES >= 30u
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramMinVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramMinVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramMaxVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramMaxVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramAvgVoltageOperational) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramAvgVoltageOperational[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramMinVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramMinVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramMaxVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramMaxVoltageStorage[0] },
    { .systemVoltageLimits       = &voltageHistogramLimitsCellVoltage[0],
      .systemVoltageLimitsLength = (sizeof(voltageHistogramLimitsCellVoltage) / sizeof(int32_t)) + 1U,
      .counterSize               = sizeof(voltageHistogramCountersModule[29].counters.countershistogramAvgVoltageStorage) / sizeof(uint32_t),
      .counters                  = &voltageHistogramCountersModule[29].counters.countershistogramAvgVoltageStorage[0] },
#endif
};

const VoltageHistogramConfig voltageHistogramConfig = {
    .histograms         = voltageHistograms,
    .numberOfHistograms = sizeof(voltageHistograms) / sizeof(VoltageHistogram)
};

//***************************************************************************//
//************************** PRIVATE FUNCTION DEFINITIONS *******************//
//***************************************************************************//

//***************************************************************************//
//************************** PUBLIC FUNCTION DEFINITIONS * ******************//
//***************************************************************************//
